rubocop_extensions:
  - "rubocop-rails"

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - log/**/*
    - home/**/*
    - node_modules/**/*
    - config/initializers/*

Style/Documentation:
  Enabled: false
Layout/ClassStructure:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15
  Exclude:
    - bin/**/*
    - db/migrate/*

Metrics/BlockLength:
  CountComments: false # count full line comments?
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*
    - app/admin/**/*

Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - bin/**/*

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 25

Metrics/ModuleLength:
  CountComments: false # count full line comments?
  Max: 200
Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - spec/spec_helper.rb
    - bin/**/*
    - config/**/*
    - db/migrate/*
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true
Rails/Delegate:
  Enabled: true
Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - app/models/chat_board.rb

Rails/FilePath:
  Enabled: false
Rails/SaveBang:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/ReturnNil:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - test/**/*
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
